### ISSUE TITLE
Implementation of MobileNetV2 instead of VGG19

### ISSUE THREAD

**Issue by nitish22066** [ayush-raj8/Krishi-Lens#1]
I have tried implementing MobileNetV2 on the tomato dataset instead of VGG19 used in the tomato.ipnyb notebook. 
Here is the code snippet of what changes I have made-
![Screenshot 2021-09-14 120943](https://user-images.githubusercontent.com/72659432/133207864-0a9defd5-c965-425d-be9f-4edd611f86c9.jpg)
![Screenshot 2021-09-14 121046](https://user-images.githubusercontent.com/72659432/133207972-5ee8b048-087c-4328-9ea6-0d995c288ce2.jpg)
The accuracy then came out to be higher than before-
![Screenshot 2021-09-14 120758](https://user-images.githubusercontent.com/72659432/133207620-cede9b0a-2d74-4b52-86c4-c55a090db6b4.jpg)
Since MobileNet uses a very efficient neural network architecture that minimizes the amount of memory and computational resources needed, while maintaining a high level of accuracy, it can be used over the previously used model.

**Comment by ayush-raj8** [comment]
@nitish22066 You can proceed with this, make your PR with jupyter notebook and model in tflite format not h5 .

**Comment by nitish22066** [comment]
@ayush-raj8 ok, will do that

**Comment by ayush-raj8** [comment]
Completed & closed
