### ISSUE TITLE
App Icon

### ISSUE THREAD

**Issue by sekocoder** [ayush-raj8/Krishi-Lens#6]
Sir,
I have designed a logo for the app and have implemented it in the project. I have also checked that it is working fine on android devices.
Sir i am new to github so i did not know we have to ask in issues before making a PR.I have implemented the app icon sir.

**Comment by sekocoder** [comment]
This is how the icon looks on android devices now sir -
![Screenshot_20211203-170130_One UI Home.jpg](https://user-images.githubusercontent.com/93031862/144606622-3f90b9e9-cb13-4725-805f-83a1f09c860f.jpg)

**Comment by ayush-raj8** [comment]
@sekocoder yes you can take

**Comment by sekocoder** [comment]
Thank you sir
